### ISSUE TITLE
Prebuilt kernel

### ISSUE THREAD

**Issue by rancidfrog** [TheStrix/twrp_device_xiaomi_sagit#1]
Which source is used to compile prebuilt kernel:
`TARGET_PREBUILT_KERNEL := device/xiaomi/sagit/prebuilt/Image.gz-dtb`

**Comment by TheStrix** [comment]
It is simply taken from MIUI and not compiled by me.

**Comment by rancidfrog** [comment]
From device?
Or, ROM Can you point out where?

Thank you

**Comment by TheStrix** [comment]
Just unpack the boot.img from MIUI ROM zip and it's the same file named "**kernel**" in it.
